[package]
name = "actix-middleware-example"
version = "0.1.0"
authors = ["Hackerchai <hackerchai.com@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
http = "0.2.1"
actix =  "0.9.0"
actix-web = "2.0.0"
actix-service = "1.0.5"
actix-rt = "1.1.1"
actix-cors = "0.2.0"
futures = "0.3.5"
failure = "0.1.8"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
derive_more = "0.99.9"
chrono = { version = "0.4.12", features = ["serde"] }
diesel = { version = "1.4.5", features = ["postgres","r2d2", "chrono"] }
diesel_migrations = "1.4.0"
dotenv = "0.15.0"
env_logger = "0.7.1"
log = "0.4.11"
jsonwebtoken = "7.2.0"
bcrypt = "0.8.1"
csv = "1.1.3"
walkdir = "2.3.1"
actix-casbin= {version = "0.3.3", default-features = false, features = [ "runtime-async-std" ]}
actix-casbin-auth = {version = "0.4.0", default-features = false, features = [ "runtime-async-std" ]}
diesel-adapter = { version = "0.7.3", default-features = false, features = ["postgres","runtime-async-std"] }
uuid = {version = "0.8.1", features = ["v4"] }
